[package]
name = "warehouse_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
tokio = {version = "1.12.0", features = ["macros", "rt"]}

